module.exports.descriptors = [
    'Bar',
    'Cafeteria',
    'Diner',
    'Inn',
    'Outlet',
    'Saloon',
    'Eatery',
    'Canteen',
    'Joint',
    'Pizzeria',
    'Club',
    'Grill House',
    'Dive',
    'Stand',
    'Fast-Food',
    'Hashery',
    'Tavern',
    'Restaurant'
]

module.exports.places = [
    'Flats',
    'Dilli',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]